/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import Control.InvoiceControl;
import Control.ProductControl;
import Control.SalespersonControl;
import Entity.Customer;
import Entity.Product;
import Entity.Salesperson;
import static Main.Main.controlfactory;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zubin
 */
public class InvoiceSubtotal extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceSubtotal
     */
    private double subT;
    private double Total;
    private double tax;
    private double comm;
    private Salesperson sp1;
    private Customer c1;
    private Double dfee;
    private HashMap<Product, Integer> order;
    private int invID;
    
    public InvoiceSubtotal(Customer c1,Salesperson s1, HashMap<Product, Integer> pList, double deliveryFee) {
        initComponents();
        this.sp1 = s1;
        this.c1 = c1;
        this.order = pList;
        this.dfee = deliveryFee;
        
        InvoiceControl inc = controlfactory.getInvoice();
        this.invID =  inc.getInvoiceID();
        subT = 0;
        
        System.out.println("Order size: " + pList.size());
        
        jTextArea1.setText("\nCustomer Name: " + c1.getFirstname() + " " + c1.getLastname()+
        "\nCustomer Phone: "+ c1.getPhone() + "\nCustomer Address:" + c1.getAddress()+ 
                "\n----------------------------------------");  
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
//        List<Salesperson> list = lst;
        Object rowData[] = new Object[3];
        //FIXME fix the product table understand product database
        pList.entrySet().stream().map(me -> {
            rowData[0] = me.getKey().getProductPK().getProductname();
            
            return me;
        }).map(me -> {
            rowData[1] = me.getKey().getProductPK().getWarehousename();
            return me;
        }).map(me -> {
            rowData[2] = me.getValue();        
//            orderLst.add(in1.addOrderItem(invID, me.getKey().getProductPK().getProductname(),
//                me.getKey().getProductPK().getWarehousename(), me.getValue()));
            subT += me.getValue() * me.getKey().getSellingprice();
            return me;
        }).forEachOrdered(_item -> {
            model.addRow(rowData);
        });
        
        
        tax = c1.getTax() / 100 * subT;
        comm = s1.getCommissionrate() / 100 * subT;
        Total = tax + subT;
        

        jTextArea3.setText(
                "\nSalesperson Name: "+ s1.getFirstname() + " " + s1.getLastname()+
                "\nSalesperson Phone: "+ s1.getPhone() +
                "\n----------------------------------------");
        //FIXME

        jTextArea2.setText ("\nSubtotal: $" + subT+ 
                "\nSales Tax: $"+ tax +
                "\nDelivery Fee: $"+ dfee +
                "\nSales Commission: $"+ comm +
                "\nTotal: $"+ Total );
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Subtotal");

        jButton2.setText("Place Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Warehouse", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setResizable(false);
            productTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String str = java.time.LocalDate.now().toString();
            InvoiceControl in1 = controlfactory.getInvoice();
            ProductControl pc = controlfactory.getProduct();
            in1.addInvoice(sp1, c1, subT, tax, comm, dfee, Total, true, str, invID);


            Iterator iterator = order.entrySet().iterator();
            while (iterator.hasNext()) {
                 HashMap.Entry me = (HashMap.Entry) iterator.next();
                 Product p = (Product)me.getKey();
                 Integer q = (Integer) me.getValue();
              in1.addOrderItem(invID, p.getProductPK().getProductname(),
                    p.getProductPK().getWarehousename(), q);
                pc.updateQuantityOrder(p.getProductPK().getProductname(), p.getProductPK().getWarehousename(), q);
            }

            //TODO update salesperson total sales/commission
            SalespersonControl sc = controlfactory.getSalesperson();

            sc.updateSalesperson(sp1, comm, subT);

            this.setVisible(false);
            new CustomerPurchase().setVisible(true);
        }
        catch (Exception e){
            this.setVisible(false);
            new CustomerPurchase().setVisible(true);
            JOptionPane.showMessageDialog(null, "Something went wrong... :(", "Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CustomerPurchase().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceSubtotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceSubtotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceSubtotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceSubtotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new InvoiceSubtotal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
